require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: ${{values.rubyVersion}}
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

# Layout
Layout/LineLength:
  Max: 120

# Metrics
Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - "config/application.rb"

# Rails
Rails/SkipsModelValidations:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test

# RSpec
RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
